### ISSUE TITLE
Head Tag not working.

### ISSUE THREAD

**Issue by mesutcakir** [entozoon/html-includes#5] opened 2018-02-06 19:46 UTC
This code not working, all codes included <body> :(

<html lang="en">
<head include="_head.html"></head>
<body>
...

**Comment by entozoon** [comment] 2018-02-07 10:10
Could you provide an example?

**Comment by entozoon** [comment] 2018-02-19 12:40
Probably a duplicate of [this issue](https://github.com/entozoon/html-includes/issues/4#issuecomment-363995172), so closing for now.

**Closed by entozoon** 2018-02-19 12:40 UTC
